name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: Packages/.cache
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.2'

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Update Homebrew
      run: |
        brew update --preinstall
        export BREW_REPO=$(brew --repository)
        cat "$BREW_REPO/Library/Taps/homebrew/homebrew-core/Formula/xcbeautify.rb" > .github/brew-xcbeautify
        cat "$BREW_REPO/Library/Taps/homebrew/homebrew-core/Formula/xcodegen.rb" > .github/brew-xcodegen

    - name: Configure Homebrew xcbeautify cache
      uses: actions/cache@v2
      with:
        path: |
          ~/Library/Caches/Homebrew/xcbeautify--*
          ~/Library/Caches/Homebrew/downloads/*--xcbeautify-*
        key: brew-${{ hashFiles('.github/brew-xcbeautify') }}
        restore-keys: brew-xcbeautify

    - name: Configure Homebrew xcodegen cache
      uses: actions/cache@v2
      with:
        path: |
          ~/Library/Caches/Homebrew/xcodegen--*
          ~/Library/Caches/Homebrew/downloads/*--xcodegen-*
        key: brew-${{ hashFiles('.github/brew-xcodegen') }}
        restore-keys: brew-xcodegen

    - name: Install Homebrew dependencies
      run: |
        env HOMEBREW_NO_AUTO_UPDATE=1 brew install xcbeautify xcodegen

    - name: Run xcodegen
      run: |
        make xcg

    - name: Run test
      run: |
        make test
